on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before checkout'
        run: ls

      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'After checkout'
        run: ls

      - name: "Login to Docker Hub"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 'Build Docker image'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/andaelaaser .

      - name: 'Push Docker image'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/andaelaaser
